runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/?.*
  script: main.app
- url: /auth/?.*
  script: auth.app
- url: /configure/?.*
  script: configure.app
- url: /google-auth/callback
  script: googleauth.app
